### ISSUE TITLE
Add support for CTL-4100K, CTL-4100WL and CTL-6100WL

### ISSUE THREAD

**Issue by amsaid1989** [tb2097/wacom-gui#20] opened 2018-08-20 11:31 UTC
Wacom seems to have updated their line-up recently with these three new models of the Wacom Intuos.

They are detected with xsetwacom and they are working fine on Linux, but I still haven't managed to set any parameters on them using xsetwacom, and they are not working with the GUI.

When I try running the GUI, this is the error I get:

> Button number does not exist on device.
Traceback (most recent call last):
  File "/usr/local/wacom-gui/wacom-gui.py", line 313, in <module>
    main()    
  File "/usr/local/wacom-gui/wacom-gui.py", line 232, in main
    window = WacomGui()
  File "/usr/local/wacom-gui/wacom-gui.py", line 25, in __init__
    self.initUI()
  File "/usr/local/wacom-gui/wacom-gui.py", line 29, in initUI
    self.pad           = Pad()
  File "/usr/local/wacom-gui/pad.py", line 22, in __init__
    self.initUI()
  File "/usr/local/wacom-gui/pad.py", line 170, in initUI
    if getCommand[0] == "button +0 \n":
IndexError: list index out of range

Any chance you can add support for them?

**Comment by tb2097** [comment] 2018-08-30 23:04
Can you please run `/usr/bin/libwacom-list-local-devices` for the tablets and let me know what the output shows as? These are all wireless tablets which I haven't worked with as of yet so it would be very helpful to get them added.

**Comment by amsaid1989** [comment] 2018-08-31 00:04
Strangely, when I run the command, I get no output at all.

This is the output I get from `xsetwacom --list devices`

> Wacom Intuos BT M Pen stylus    	id: 12	type: STYLUS    
Wacom Intuos BT M Pen eraser    	id: 13	type: ERASER    
Wacom Intuos BT M Pen cursor    	id: 14	type: CURSOR    
Wacom Intuos BT M Pad pad       	id: 15	type: PAD

Just to let you know, these tablets are not wireless only. They can be attached using USB as well.

**Comment by jcpearson** [comment] 2018-08-31 09:15
`libwacom-list-local-devices` is part of the libwacom package and effectively just pretty-prints the contents of the matching `/usr/share/libwacom/ *.tablet` files (which are also part of the libwacom package) of attached Wacom tablets

The version of libwacom that ships with RHEL/CentOS 7 (version 0.24) doesn't have `.tablet` files for these newer tablets

You could download the latest libwacom source (v0.31) from https://github.com/linuxwacom/libwacom/releases, extract the required `.tablet` file(s) and copy them to `/usr/share/libwacom/` - then `libwacom-list-local-devices` _should_ give the required output for these newer tablets

However, the libwacom source ships with another utility (`list-devices` - which is not installed by default) that gives a similar output to that of `libwacom-list-local-devices` - but for all `.tablet` files, not just the attached Wacom tablets - i.e. you don't need to have a tablet to get the output - but you will need the latest libwacom source to get the newer `.tablet` files and to build the `list-devices` utility

**Comment by amsaid1989** [comment] 2018-08-31 15:53
Thank you very much. I downloaded the files, copied them, and this is the output I get from `libwacom-list-local-devices`.

For some reason, the output seems to be printed twice. Since I haven't used `libwacom-list-local-devices` before, I am not sure if that is the normal behavior or not.

> [Device]
Name=Wacom Intuos BT M
DeviceMatch=usb:056a:0378;bluetooth:056a:0379;
Class=Bamboo
Width=10
Height=8
IntegratedIn=
Layout=intuos-m-p3.svg
Styli=0x862;
> 
> [Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
StatusLEDs=
NumStrips=0
Buttons=4
[Buttons]
Left=
Right=
Top=A;B;C;D;
Bottom=
Touchstrip=
Touchstrip2=
OLEDs=
Ring=
Ring2=
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0
> 
> _______________________________
> [Device]
Name=Wacom Intuos BT M
DeviceMatch=usb:056a:0378;bluetooth:056a:0379;
Class=Bamboo
Width=10
Height=8
IntegratedIn=
Layout=intuos-m-p3.svg
Styli=0x862;
> 
> [Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=false
TouchSwitch=false
StatusLEDs=
NumStrips=0
Buttons=4
[Buttons]
Left=
Right=
Top=A;B;C;D;
Bottom=
Touchstrip=
Touchstrip2=
OLEDs=
Ring=
Ring2=
RingNumModes=0
Ring2NumModes=0
StripsNumModes=0

**Comment by amsaid1989** [comment] 2018-08-31 16:53
Unfortunately, my Linux PC doesn't have Bluetooth, so I can't use the tablet wirelessly. I will install Linux on my laptop and see if I can get it to recognize the tablet wirelessly.

**Comment by amsaid1989** [comment] 2018-08-31 18:06
I have installed Ubuntu 18.04 and managed to pair and connect the tablet to my laptop's Bluetooth device, but it doesn't do anything and it is not recognized by `xsetwacom`. Not sure if that will help, but when I was connecting it to the Bluetooth, it was recognized as `Intuos BT M` which is the name I am getting from `xsetwacom` when connecting with the USB cable.

Hope that could be helpful. I will continue to try getting it to work on my laptop using Bluetooth and I will update you if I succeed.

**Comment by tb2097** [comment] 2018-08-31 21:54
I'll go with the assumption for now.  It'll take a little bit since I'm converting to use `libwacom-list-local-devices` so I need to update how it collects information about the tablet.  I plan to include the *.tablet & layout files from libwacom-0.31 in the package but it'll check the local version first (if that makes sense).  I'll look into the wireless support later if I can get what `xsetwacom` reports other models as in wired vs wireless mode.

**Comment by amsaid1989** [comment] 2018-08-31 22:15
Thank you very much. Take all the time you need. This is not an urgent issue anyway since the tablet is working.

I think it is a good idea to include the *.tablet files, seeing that not all the distros will have the newest version of libwacom.

**Comment by jcpearson** [comment] 2018-09-03 13:10
> For some reason, the output seems to be printed twice. Since I haven't used
> libwacom-list-local-devices before, I am not sure if that is the normal behavior or not.

`libwacom-list-local-devices` searches /dev/input/event* for Wacom devices - and as 'Pen' and 'Finger Touch' are reported as separate input devices, you get the output twice - e.g. with a 'Intuos Pro M', `dmesg` reports:

```
[4233463.031100] input: Wacom Intuos Pro M Pen as /devices/pci0000:00/0000:00:1c.0/0000:02:00.0/usb3/3-2/3-2:1.0/input/input16
[4233463.044174] input: Wacom Intuos Pro M Finger as /devices/pci0000:00/0000:00:1c.0/0000:02:00.0/usb3/3-2/3-2:1.1/input/input17
```
and `libwacom-list-local-devices` reports the 'Wacom Intuos Pro M' twice - so I guess it is expected behaviour ...

**Comment by tb2097** [comment] 2018-11-22 00:55
@amsaid1989 Please test the new release, it should resolve the uses if it's a valid device.
https://github.com/tb2097/wacom-gui/releases/tag/v0.3.0-rc1

**Comment by tb2097** [comment] 2018-11-29 16:52
Closing this issue as it is related to the 0.2.x releases and I have no plans to further maintain it.  If the new GUI should support the devices as they are reported correctly in libwacom.

**Closed by tb2097** 2018-11-29 16:52 UTC
