### ISSUE TITLE
Crash when using tablets that have different device names

### ISSUE THREAD

**Issue by jcpearson** [tb2097/wacom-gui#11] opened 2018-06-05 10:43 UTC
When using a Intuos Pro M (PTH-651), wacom-gui crashes with:

```
Cannot find device 'Wacom Intuos Pro M Finger  touch'.
Traceback (most recent call last):
  File "/usr/local/wacom-gui/wacom-gui.py", line 305, in <module>
    main()    
  File "/usr/local/wacom-gui/wacom-gui.py", line 218, in main
    window = WacomGui()
  File "/usr/local/wacom-gui/wacom-gui.py", line 25, in __init__
    self.initUI()
  File "/usr/local/wacom-gui/wacom-gui.py", line 33, in initUI
    self.touch = touch(self.pad.Tablet.deviceNames['touch'])
  File "/usr/local/wacom-gui/touch.py", line 16, in __init__
    self.initUI()
  File "/usr/local/wacom-gui/touch.py", line 27, in initUI
    self.getEnableStatus()
  File "/usr/local/wacom-gui/touch.py", line 47, in getEnableStatus
    if getCommand[0] == "on\n":
IndexError: list index out of range
```

Not sure why touch.py is re-assigning 'tabletName' - as it already has it set correctly ???

The following patch tidies this all up - plus removes a later unnecessary check :

```
--- ./wacom-gui/touch.py.dist   2018-05-28 17:13:39.000000000 +0100
+++ ./wacom-gui/touch.py        2018-06-05 10:54:55.279117673 +0100
@@ -6,20 +6,14 @@ import sys, os, re
 class touch(QtGui.QWidget):
     def __init__(self, tabletName, parent=None):
         QtGui.QWidget.__init__(self, parent)
-        devices = os.popen("xsetwacom --list devices").readlines()
-        self.tabletName = None
-        for device in devices:
-            attr = device.strip().split('\t')
-            if attr[2] == 'type: TOUCH':
-                self.tabletName = attr[0][:-6]
-                self.enable = None
+        if tabletName ==  "":
+            return None
+        self.tabletName = tabletName
+        self.enable = None
         self.initUI()
 
     def initUI(self):
         self.devices = []
-        # check if it is even necessary
-        if os.popen("xsetwacom --list devices | grep touch").readlines().__len__() == 0:
-            return None
         # layout code
         self.mainLayout = QtGui.QHBoxLayout()
         self.mainLayout.setAlignment(QtCore.Qt.AlignLeft)
```

**Comment by AlexWoodrowPCL** [comment] 2018-06-05 11:26
Just encountered this error on CentOS 7 using a PTH-660 - the suggested changes appear to fix the issue.

**Comment by tb2097** [comment] 2018-06-05 18:23
I had seen this issue with another user but only had a PTH-650 to test with, which didn't show the same error.
The issue is the tablet name was having an extra space at the end so the constructed string was invalid.  Whitespace is now stripped from the end of device names to ensure correct naming, as well as having the device list default to _None_ value for more correct check.  V0.2.1-3 will be released soon.
```
'Wacom Intuos Pro M Finger  touch'
'Wacom Intuos Pro M Finger touch'
```

**Closed by tb2097** 2018-06-05 18:23 UTC
