### ISSUE TITLE
Tablet maps to 'wrong' screen if screen order is reversed

### ISSUE THREAD

**Issue by jcpearson** [tb2097/wacom-gui#4] opened 2018-04-06 12:56 UTC
Another issue:

wacom-gui assumes 'Screen 0' is the left monitor, but if the order of the monitors is changed, then it maps the tablet to the 'other' screen

I believe the following patch fixes this - it sets the screen with the lowest top left x-coordinate to be the left screen (and also use round() when comparing screen coordinates)

```
--- ./wacom-gui/options.py.dist 2018-02-02 18:10:47.000000000 +0000
+++ ./wacom-gui/options.py      2018-04-06 12:03:48.677251539 +0100
@@ -15,6 +15,7 @@ class otherOptions(QtGui.QWidget):
         self.devices = []
         self.tabletActiveArea = ""
         self.orient = ''
+        self.screenOrder = [0, 1]
         
         #layout code
         self.mainLayout = QtGui.QHBoxLayout()
@@ -105,9 +106,9 @@ class otherOptions(QtGui.QWidget):
                     #    if self.otherOptionSettings[i].find("xinput set-prop") != -1 and self.otherOptionSettings[i].find(device) != -1:
                     #        self.otherOptionSettings[i] =  "xinput set-prop \"" + device + "\" --type=float \"Coordinate Transformation Matrix\" 1 0 0 0 1 0 0 0 1"
         elif buttonId.text() == "Left Monitor":
-            screen = QtGui.QDesktopWidget().screenGeometry(0)
+            screen = QtGui.QDesktopWidget().screenGeometry(self.screenOrder[0])
         elif buttonId.text() == "Right Monitor":
-            screen = QtGui.QDesktopWidget().screenGeometry(1)
+            screen = QtGui.QDesktopWidget().screenGeometry(self.screenOrder[1])
         if screen != "":
             totalResolution = os.popen("xdpyinfo | grep dimensions | awk '{print $2}' | awk -Fx '{print $1, $2}'").read()
             totalResolution = totalResolution.split()
@@ -164,6 +165,13 @@ class otherOptions(QtGui.QWidget):
         else:
             screen1 = QtGui.QDesktopWidget().screenGeometry(0)
             screen2 = QtGui.QDesktopWidget().screenGeometry(1)
+
+            # check order of screens - screen with the lowest x coord
+            # is assumed to be the left screen
+            if screen1.topLeft().x() > screen2.topLeft().x():
+                self.screenOrder = [1, 0]
+                (screen2, screen1) = (screen1, screen2)
+
             totalResolution = os.popen("xdpyinfo | grep dimensions | awk '{print $2}' | awk -Fx '{print $1, $2}'").read()
             totalResolution = totalResolution.split()
 
@@ -184,7 +192,7 @@ class otherOptions(QtGui.QWidget):
             isLeft = True
             for i in range(0,3):
                 for j in range(0,3):
-                    if float(tabletScreenCoords[(i,j)]) != float(display[i][j]):
+                    if round(float(tabletScreenCoords[(i,j)]),6) != round(float(display[i][j]),6):
                         isLeft = False
                         break
 
@@ -205,7 +213,7 @@ class otherOptions(QtGui.QWidget):
                 isRight = True
                 for i in range(0,3):
                     for j in range(0,3):
-                        if float(tabletScreenCoords[(i,j)]) != float(display[i][j]):
+                        if round(float(tabletScreenCoords[(i,j)]),6) != round(float(display[i][j]),6):
                             isRight = False
                             break
                 if isRight:

```

**Comment by tb2097** [comment] 2018-04-06 18:33
It'll take a little bit of time but I think I'd prefer to redo this chunk of code using MapToOutput.  The transform matrix method is horribly kludgy but at the time I wrote it originally MapToOutput wasn't an option.  It will also allow me to properly support more than 2 monitors but this might take a bit to test/flesh out properly.

**Comment by tb2097** [comment] 2018-05-09 19:40
New release posted.  It uses display order in accordance to how it is detected by the OS so if someone puts their displays in an odd order it might jump around.  However, it should map correctly to any screen layout.  Please test if this works better for you:
https://github.com/tb2097/wacom-gui/releases/tag/V0.1.10

**Comment by jcpearson** [comment] 2018-05-10 14:25
Fails if you only have one monitor:

```
Traceback (most recent call last):
  File "wacom-gui.py", line 249, in <module>
    main()    
  File "wacom-gui.py", line 182, in main
    window = WacomGui()
  File "wacom-gui.py", line 23, in __init__
    self.initUI()
  File "wacom-gui.py", line 32, in initUI
    self.options       = otherOptions(self.pad.Tablet.Name)
  File "/tmp/wacom-gui-master/wacom-gui/options.py", line 14, in __init__
    self.initUI()
  File "/tmp/wacom-gui-master/wacom-gui/options.py", line 32, in initUI
    self.getCurrentScreen()
  File "/tmp/wacom-gui-master/wacom-gui/options.py", line 234, in getCurrentScreen
    self.screenLeft.enabled = False 
AttributeError: 'otherOptions' object has no attribute 'screenLeft'
```

I believe the following patch fixes this:

```
--- options.py.dist     2018-05-09 20:29:53.000000000 +0100
+++ options.py  2018-05-10 15:15:25.578078059 +0100
@@ -230,14 +230,8 @@ class otherOptions(QtGui.QWidget):
 
     def getCurrentScreen(self):
         # check if we actually have more that 1 screen
-        if QtGui.QDesktopWidget().numScreens() < 2 or QtGui.QDesktopWidget().numScreens() > 2:
-            self.screenLeft.enabled = False 
-            self.screenRight.enabled = False 
-            self.screenFull.enabled = False 
-            if QtGui.QDesktopWidget().numScreens() > 2:
-                print "More that 2 monitors; this isn't available yet.  Disabling tablet area option"
+        if QtGui.QDesktopWidget().numScreens() > 1:
         # set correct check box for active area... if it is valid
-        else:
             self.getTabletArea()
     
     def setDevices(self, devices):
```

Otherwise, appears to work - although I don't have access to a machine with more than 2 monitors to see it that works OK (works with 2 monitors)

**Comment by tb2097** [comment] 2018-05-11 15:58
Patch implemented.  I only tested the 2/3 screen setup, which is why I missed the legacy code that should've been removed.  Please verify the new release is working as intended.

**Comment by jcpearson** [comment] 2018-05-11 16:46
Still fails :-)

```
Traceback (most recent call last):
  File "wacom-gui.py", line 249, in <module>
    main()    
  File "wacom-gui.py", line 182, in main
    window = WacomGui()
  File "wacom-gui.py", line 23, in __init__
    self.initUI()
  File "wacom-gui.py", line 32, in initUI
    self.options       = otherOptions(self.pad.Tablet.Name)
  File "/usr/local/wacom-gui/options.py", line 13, in __init__
    self.initUI()
  File "/usr/local/wacom-gui/options.py", line 29, in initUI
    self.getCurrentScreen()
  File "/usr/local/wacom-gui/options.py", line 167, in getCurrentScreen
    self.screenFull.enabled = False
AttributeError: 'otherOptions' object has no attribute 'screenFull'
```
The issue is that self.screenFull is not defined when there is only one monitor - as screenOptions() does:

```
    def screenOptions(self):
        if QtGui.QDesktopWidget().numScreens() == 1:
            return None
```
i.e. returns None _before_ self.screenFull is set up ...

**Comment by tb2097** [comment] 2018-05-11 21:13
nuked getCurrentScreen() function and just call getTabletArea() if multiple screens are detected (I really need to do a proper code cleanup...).  Replaced the downloads on the latest release as it was a very minor change.

**Comment by tb2097** [comment] 2018-05-14 18:12
Closing issue

**Closed by tb2097** 2018-05-14 18:12 UTC
